package com.myapp.aws.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;
import java.util.Map;

@DynamoDBTable(tableName = "AccountNumberFormat")
public class AccountNumberFormat{
    private String modificationFlag;
    private String isoCountryCode;
    private String recordKey;
    private String countryName;
    private String accountNbType;
    private String regexFormat;
    private Integer minLength;
    private Integer maxLength;
    private Date lastUpdatedDate;

    @DynamoDBAttribute(attributeName="modificationFlag")
    public String getModificationFlag() {
        return modificationFlag;
    }

    public void setModificationFlag(String modificationFlag) {
        this.modificationFlag = modificationFlag;
    }

    @DynamoDBHashKey(attributeName="isoCountryCode")
    public String getIsoCountryCode() {
        return isoCountryCode;
    }

    public void setIsoCountryCode(String isoCountryCode) {
        this.isoCountryCode = isoCountryCode;
    }

    @DynamoDBAttribute(attributeName = "recordKey")
    public String getRecordKey() {
        return recordKey;
    }

    public void setRecordKey(String recordKey) {
        this.recordKey = recordKey;
    }

    @DynamoDBAttribute(attributeName = "countryName")
    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    @DynamoDBAttribute(attributeName = "accountNumberType")
    public String getAccountNbType() {
        return accountNbType;
    }

    public void setAccountNbType(String accountNbType) {
        this.accountNbType = accountNbType;
    }

    @DynamoDBAttribute(attributeName = "regexFormat")
    public String getRegexFormat() {
        return regexFormat;
    }

    public void setRegexFormat(String regexFormat) {
        this.regexFormat = regexFormat;
    }

    @DynamoDBAttribute(attributeName = "minLength")
    public Integer getMinLength() {
        return minLength;
    }

    public void setMinLength(Integer minLength) {
        this.minLength = minLength;
    }
    public void setMinLength(String minLength) {
        if(minLength != null && !minLength.isEmpty()) {
            this.minLength = Integer.valueOf(minLength);
        }
    }

    @DynamoDBAttribute(attributeName = "maxLength")
    public Integer getMaxLength() {
        return maxLength;
    }

    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
    }

    public void setMaxLength(String maxLength) {
        if(maxLength != null && !maxLength.isEmpty()) {
            this.maxLength = Integer.valueOf(maxLength);
        }
    }

    @DynamoDBAttribute(attributeName = "lastUpdatedTime")
    @DynamoDBAutoGeneratedTimestamp(strategy= DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    public AccountNumberFormat(){

    }

    public AccountNumberFormat(Map<String, String> records){
        setModificationFlag(records.get("MODIFICATION FLAG"));
        setIsoCountryCode(records.get("ISO COUNTRY CODE"));
        setRecordKey(records.get("RECORD KEY"));
        setCountryName(records.get("COUNTRY NAME"));
        setAccountNbType(records.get("ACCOUNT NB TYPE"));
        setRegexFormat(records.get("REGEX FORMAT"));
        setMinLength(records.get("MIN LENGTH"));
        setMaxLength(records.get("MAX LENGTH"));
    }


}