package com.myapp.aws.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Map;

@DynamoDBTable(tableName = "IbanPlus")
public class IbanPlus{
    private String nationalIdCountry;
    private String modificationFlag;
    private String recordKey;
    private String institutionName;
    private String countryName;
    private String isoCountryCode;
    private String ibanIsoCountryCode;
    private String ibanBic;
    private String routingBic;
    private String ibanNationalId;
    private String serviceContext;
    private String lastUpdatedDate;

    @DynamoDBHashKey(attributeName = "nationalIdCountry")
    public String getNationalIdCountry() {
        return nationalIdCountry;
    }

    public void setNationalIdCountry(String nationalIdCountry) {
        this.nationalIdCountry = nationalIdCountry;
    }

    @DynamoDBIgnore
    public String getModificationFlag() {
        return modificationFlag;
    }

    public void setModificationFlag(String modificationFlag) {
        this.modificationFlag = modificationFlag;
    }

    @DynamoDBAttribute(attributeName="recordKey")
    public String getRecordKey() {
        return recordKey;
    }

    public void setRecordKey(String recordKey) {
        this.recordKey = recordKey;
    }

    @DynamoDBAttribute(attributeName="institutionName")
    public String getInstitutionName() {
        return institutionName;
    }

    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    @DynamoDBAttribute(attributeName="countryName")
    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    @DynamoDBAttribute(attributeName="isoCountryCode")
    public String getIsoCountryCode() {
        return isoCountryCode;
    }

    public void setIsoCountryCode(String isoCountryCode) {
        this.isoCountryCode = isoCountryCode;
    }

    @DynamoDBAttribute(attributeName="ibanIsoCountryCode")
    public String getIbanIsoCountryCode() {
        return ibanIsoCountryCode;
    }

    public void setIbanIsoCountryCode(String ibanIsoCountryCode) {
        this.ibanIsoCountryCode = ibanIsoCountryCode;
    }

    @DynamoDBAttribute(attributeName="ibanBic")
    public String getIbanBic() {
        return ibanBic;
    }

    public void setIbanBic(String ibanBic) {
        this.ibanBic = ibanBic;
    }

    @DynamoDBAttribute(attributeName="routingBic")
    public String getRoutingBic() {
        return routingBic;
    }

    public void setRoutingBic(String routingBic) {
        this.routingBic = routingBic;
    }

    @DynamoDBAttribute(attributeName="ibanNationalId")
    public String getIbanNationalId() {
        return ibanNationalId;
    }

    public void setIbanNationalId(String ibanNationalId) {
        this.ibanNationalId = ibanNationalId;
    }

    @DynamoDBAttribute(attributeName="serviceContext")
    public String getServiceContext() {
        return serviceContext;
    }

    public void setServiceContext(String serviceContext) {
        this.serviceContext = serviceContext;
    }

    @DynamoDBAttribute(attributeName = "lastUpdatedTime")
    @DynamoDBAutoGeneratedTimestamp(strategy= DynamoDBAutoGenerateStrategy.ALWAYS)
    public String getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(String lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    public IbanPlus(){

    }

    public IbanPlus(Map<String, String> records){
        setNationalIdCountry(records.get("IBAN NATIONAL ID") + "-" + records.get("ISO COUNTRY CODE"));
        setModificationFlag(records.get("MODIFICATION FLAG"));
        setRecordKey(records.get("RECORD KEY"));
        setInstitutionName(records.get("INSTITUTION NAME"));
        setCountryName(records.get("COUNTRY NAME"));
        setIsoCountryCode(records.get("ISO COUNTRY CODE"));
        setIbanIsoCountryCode(records.get("IBAN ISO COUNTRY CODE"));
        setIbanBic(records.get("IBAN BIC"));
        setRoutingBic(records.get("ROUTING BIC"));
        setIbanNationalId(records.get("IBAN NATIONAL ID"));
        setServiceContext(records.get("SERVICE CONTEXT"));
    }
}
